INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Piedad Olson', 'Textbook', 39.76, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tamera Heller', 'Folklore', 28.72, 'Endless Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Paige VonRueden', 'Mythopoeia', 31.8, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Steven Heaney', 'Realistic fiction', 38, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Homer McCullough II', 'Tall tale', 35.12, 'Noli Me Tangere');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Kris Ullrich', 'Speech', 27.96, 'A Darkling Plain');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Catrina Conn', 'Fiction in verse', 39.72, 'Consider the Lilies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Arron Pagac', 'Science fiction', 13.68, 'The Wealth of Nations');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lewis Block', 'Folklore', 42.88, 'Of Mice and Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Perry Oberbrunner PhD', 'Reference book', 43.36, 'The Monkey\'s Raincoat');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Isiah Bauch', 'Science fiction', 28.24, 'Taming a Sea Horse');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maira Fadel', 'Mythology', 20.89, 'The Other Side of Silence');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lance Marquardt', 'Science fiction', 15.91, 'The Doors of Perception');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Domingo Torp', 'Mystery', 31.7, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leonard Braun', 'Western', 31.68, 'Blithe Spirit');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Thomasina Bailey', 'Historical fiction', 33.79, 'I Will Fear No Evil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Corliss Feil', 'Tall tale', 10.25, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Woodrow Moen', 'Mystery', 14.73, 'Rosemary Sutcliff');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Janita Lubowitz', 'Comic/Graphic Novel', 27.29, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Ciara Barton', 'Legend', 18.26, 'The Way of All Flesh');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Darell Goldner', 'Fiction in verse', 10.16, 'Number the Stars');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Alona Waters', 'Essay', 22, 'A Farewell to Arms');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Adelaide Corkery Jr.', 'Folklore', 21.78, 'The Needle\'s Eye');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Isaiah Ferry', 'Suspense/Thriller', 41.1, 'To Say Nothing of the Dog');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hal Jast', 'Realistic fiction', 38.48, 'The Moving Finger');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Max Boyle', 'Realistic fiction', 44.88, 'After Many a Summer Dies the Swan');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sheldon Koepp', 'Fiction in verse', 45.8, 'By Grand Central Station I Sat Down and Wept');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Yesenia Ebert', 'Reference book', 31.05, 'Gone with the Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Daniel Hessel', 'Short story', 12.14, 'Waiting for the Barbarians');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lupe Streich', 'Textbook', 29.16, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carmine Kerluke', 'Mythopoeia', 22.45, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Jerome Sawayn', 'Biography/Autobiography', 25.02, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ammie Hessel', 'Fairy tale', 35.97, 'A Many-Splendoured Thing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jannie Gottlieb', 'Speech', 32.48, 'Tender Is the Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Florencio Powlowski', 'Narrative nonfiction', 24.35, 'Of Human Bondage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lynnette Cartwright', 'Narrative nonfiction', 23.25, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Elenora Wisoky', 'Metafiction', 15.65, 'A Glass of Blessings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Pablo Gutmann', 'Metafiction', 33.51, 'A Time to Kill');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Apolonia Rempel', 'Realistic fiction', 16.02, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Larisa Nicolas', 'Science fiction', 29.55, 'Fair Stood the Wind for France');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Andre Hills', 'Comic/Graphic Novel', 15.35, 'Of Human Bondage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Perry Grimes', 'Short story', 27.35, 'Vile Bodies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Peg Terry', 'Fairy tale', 21.86, 'The Mermaids Singing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Edison Daniel', 'Biography/Autobiography', 21.9, 'A Monstrous Regiment of Women');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Wilmer Lowe', 'Fiction in verse', 34.4, 'The Skull Beneath the Skin');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Stephen Renner', 'Fiction narrative', 21.06, 'Nine Coaches Waiting');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Delilah Price', 'Narrative nonfiction', 29.98, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rubin Robel', 'Textbook', 27.92, 'The Needle\'s Eye');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Marty Kulas', 'Crime/Detective', 41.63, 'Great Work of Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nina Green', 'Short story', 24.7, 'No Highway');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jenise Pollich', 'Narrative nonfiction', 17.13, 'Mr Standfast');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kaila Glover', 'Comic/Graphic Novel', 11.69, 'The Golden Apples of the Sun');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Minerva Hudson', 'Western', 26.7, 'Quo Vadis');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Many Marks', 'Biography/Autobiography', 36.99, 'Stranger in a Strange Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Rich Schaefer', 'Fiction narrative', 19.49, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Nicolas Erdman', 'Crime/Detective', 39.42, 'I Will Fear No Evil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lorenzo Greenholt I', 'Suspense/Thriller', 45.6, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jed Hand', 'Western', 22.44, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lanny Orn', 'Realistic fiction', 32.72, 'The Moon by Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Jonathon Grant', 'Legend', 21.42, 'The Wives of Bath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Eduardo Daugherty', 'Fiction in verse', 37.92, 'Surprised by Joy');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Michaela Keeling PhD', 'Fiction narrative', 38.98, 'What\'s Become of Waring');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Antionette Schmitt', 'Narrative nonfiction', 33.08, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rosalyn Jerde', 'Science fiction', 38.82, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sanford Lebsack', 'Classic', 24.85, 'Terrible Swift Sword');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Logan Okuneva', 'Metafiction', 16.14, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charisse Pacocha DVM', 'Fiction narrative', 44.48, 'Of Human Bondage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dario Zieme', 'Mythology', 35.13, 'The Far-Distant Oxus');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marget Kerluke', 'Speech', 39.09, 'The Skull Beneath the Skin');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cletus Nikolaus MD', 'Folklore', 24.01, 'The Moving Finger');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Zina Bednar', 'Tall tale', 23.38, 'The Wings of the Dove');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hannelore Padberg', 'Classic', 11.11, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Keri Russel PhD', 'Fantasy', 15.41, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Anita Fay', 'Fairy tale', 30.9, 'The Green Bay Tree');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Taylor Mraz DVM', 'Tall tale', 26.58, 'Many Waters');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Felecia Gibson', 'Biography/Autobiography', 43.02, 'Everything is Illuminated');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maurice Williamson III', 'Science fiction', 25.36, 'The Skull Beneath the Skin');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dave Botsford', 'Mythopoeia', 45.08, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Fletcher Douglas', 'Metafiction', 37.22, 'Françoise Sagan');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Lakia Hand', 'Short story', 16.62, 'Consider the Lilies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shenna Green', 'Textbook', 13.39, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deandrea Goldner', 'Fiction narrative', 23.45, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Myron Leannon', 'Crime/Detective', 30.59, 'Behold the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Duncan Veum', 'Folklore', 39.08, 'Lilies of the Field');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Derick Howell', 'Historical fiction', 30.69, 'Tirra Lirra by the River');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jennell Stracke', 'Short story', 28.01, 'The Glory and the Dream');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Royce Franecki', 'Short story', 22.98, 'The Other Side of Silence');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leisha Abbott MD', 'Crime/Detective', 36.95, 'As I Lay Dying');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Thalia Jacobson', 'Fiction narrative', 17.44, 'Eyeless in Gaza');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Celsa Wilderman', 'Essay', 10.28, 'The Mermaids Singing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kristeen Pacocha', 'Realistic fiction', 28.2, 'Tiger! Tiger!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Noe Leuschke', 'Tall tale', 23.08, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Landon Lang', 'Biography/Autobiography', 24.99, 'No Highway');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Willis Morar', 'Horror', 42.07, 'The Wives of Bath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Grace Ullrich', 'Mythopoeia', 13.69, 'The Curious Incident of the Dog in the Night-Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Gaylord Harber', 'Humor', 26.6, 'The Line of Beauty');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Garland Hagenes MD', 'Reference book', 14.11, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Ashley Casper', 'Reference book', 41.56, 'Waiting for the Barbarians');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kaitlyn Johns', 'Mythopoeia', 32.65, 'The Little Foxes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dusty Zulauf', 'Classic', 31.32, 'Now Sleeps the Crimson Petal');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tiffiny Collins', 'Humor', 15.09, 'The Waste Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Damian Bechtelar', 'Essay', 21.96, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rodrigo McGlynn V', 'Science fiction', 14.51, 'Things Fall Apart');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Isaias McLaughlin', 'Metafiction', 31.39, 'Beneath the Bleeding');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Noah Purdy', 'Science fiction', 25.17, 'Dance Dance Dance');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nathaniel Wolff', 'Horror', 47.15, 'Those Barren Leaves, Thrones, Dominations');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Cyril Bednar', 'Narrative nonfiction', 44.15, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maya Okuneva DVM', 'Humor', 14.78, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Williams Waelchi', 'Classic', 37.91, 'Vanity Fair');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kindra Bartell', 'Comic/Graphic Novel', 38.34, 'The Monkey\'s Raincoat');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Bernard Flatley', 'Fiction narrative', 39.27, 'The Road Less Traveled');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nancy Bogisich', 'Textbook', 22.22, 'All the King\'s Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lynda Bogan', 'Suspense/Thriller', 35.48, 'A Many-Splendoured Thing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Chris Crooks', 'Mystery', 28.78, 'The World, the Flesh and the Devil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Reinaldo Goyette', 'Classic', 43.52, 'Recalled to Life');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lesha Glover', 'Fantasy', 29.3, 'The Wings of the Dove');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ezequiel Dach III', 'Comic/Graphic Novel', 17.53, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Erika Rice', 'Crime/Detective', 46.91, 'A Summer Bird-Cage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jonnie Hane', 'Folklore', 30.78, 'Death Be Not Proud');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Melodie Reichert', 'Legend', 38.79, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Quinn Reichert', 'Fable', 18.22, 'Blithe Spirit');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Karyn Rowe', 'Textbook', 43.84, 'Time To Murder And Create');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gertie Blick', 'Historical fiction', 40.07, 'Postern of Fate');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hipolito Ward', 'Metafiction', 44.08, 'Antic Hay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Allen Swift', 'Mystery', 47.89, 'The Mirror Crack\'d from Side to Side');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Milton Volkman', 'Mystery', 18.47, 'The Golden Apples of the Sun');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sandy Kilback', 'Textbook', 17.97, 'The Widening Gyre');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nellie Lind', 'Mythopoeia', 15.51, 'Of Mice and Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sade Feest', 'Tall tale', 35.93, 'The Glory and the Dream');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shaunta Torphy', 'Essay', 16.24, 'A Monstrous Regiment of Women');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leah DuBuque', 'Suspense/Thriller', 33.17, 'The Cricket on the Hearth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Edward O\'Keefe', 'Reference book', 44.01, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lashaun Brekke', 'Speech', 34.3, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carri Koch', 'Fable', 11.3, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Preston Carter', 'Short story', 36.63, 'Gone with the Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Joya Wolf', 'Horror', 35.96, 'Dance Dance Dance');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Arden Hane', 'Crime/Detective', 42.94, 'Fair Stood the Wind for France');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Bud Shanahan', 'Textbook', 35.49, 'A Confederacy of Dunces');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cuc Wilkinson', 'Comic/Graphic Novel', 10.94, 'Where Angels Fear to Tread');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Jude Nolan', 'Comic/Graphic Novel', 35.01, 'Nectar in a Sieve');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Enda Gislason PhD', 'Realistic fiction', 20.83, 'In Death Ground');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carol Lakin', 'Fantasy', 20.11, 'The Grapes of Wrath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kennith Pollich', 'Science fiction', 16.09, 'The Last Enemy');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Reanna Sawayn', 'Comic/Graphic Novel', 21.41, 'That Hideous Strength');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lester Grimes', 'Science fiction', 19.45, 'No Country for Old Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nichol Powlowski', 'Essay', 42.76, 'Absalom, Absalom!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Juana Brown', 'Crime/Detective', 35.59, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tory Casper', 'Historical fiction', 14.67, 'Those Barren Leaves, Thrones, Dominations');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ken Sauer', 'Short story', 47.47, 'An Evil Cradling');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Catheryn Dietrich', 'Crime/Detective', 23.02, 'Beneath the Bleeding');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Joesph Dare', 'Comic/Graphic Novel', 35.59, 'The Violent Bear It Away');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Olin Shields', 'Fairy tale', 12.28, 'Antic Hay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Donella Swaniawski PhD', 'Realistic fiction', 23.81, 'Stranger in a Strange Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Patrick Towne', 'Fantasy', 30.02, 'Mother Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gwendolyn Swift', 'Reference book', 23.61, 'Oh! To be in England');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Preston Morar II', 'Humor', 16.68, 'No Longer at Ease');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Reed Dicki Sr.', 'Crime/Detective', 19.63, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Norris Spinka', 'Suspense/Thriller', 42.33, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Renaldo Mitchell', 'Narrative nonfiction', 12.37, 'The Widening Gyre');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Lesia Bashirian', 'Humor', 45.21, 'Down to a Sunless Sea');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Thomas Satterfield', 'Horror', 24.33, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Adan McGlynn', 'Short story', 39.47, 'Brandy of the Damned');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Anika Schiller', 'Western', 32.65, 'The Skull Beneath the Skin');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Damian Veum', 'Crime/Detective', 14.2, 'Number the Stars');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Adelia Marks', 'Mythopoeia', 40.52, 'The Curious Incident of the Dog in the Night-Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jerri Goldner', 'Mystery', 19.1, 'The Sun Also Rises');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rusty Farrell', 'Historical fiction', 23.73, 'Absalom, Absalom!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Bernard Zemlak', 'Classic', 42.63, 'Blue Remembered Earth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Benjamin Boyle', 'Short story', 25.43, 'Alone on a Wide, Wide Sea');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Art O\'Hara', 'Suspense/Thriller', 29.74, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Consuelo Glover', 'Reference book', 18.21, 'To Your Scattered Bodies Go');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Jeannette Schamberger', 'Fanfiction', 11.39, 'Shall not Perish');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maile Powlowski', 'Fiction narrative', 39.22, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Nannette Kuvalis', 'Fiction in verse', 20.6, 'The Torment of Others');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Pedro Mante', 'Suspense/Thriller', 17.86, 'The Waste Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cathey Hirthe', 'Suspense/Thriller', 12.26, 'Mr Standfast');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Miles Oberbrunner', 'Fanfiction', 19.38, 'The Mermaids Singing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Reinaldo Farrell', 'Short story', 12.19, 'Such, Such Were the Joys');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Delila Johnston IV', 'Essay', 32.7, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nyla Towne', 'Realistic fiction', 17.73, 'Terrible Swift Sword');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Mozell Franecki', 'Classic', 10.17, 'Clouds of Witness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Russ Glover', 'Mythology', 22.72, 'All the King\'s Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Barry Kunze', 'Fiction in verse', 15.6, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Enrique Brown', 'Western', 46.38, 'Mother Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shala Renner', 'Humor', 16.44, 'Little Hands Clapping');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Vito Ondricka I', 'Biography/Autobiography', 17.12, 'The Monkey\'s Raincoat');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Johnie Osinski', 'Textbook', 19.54, 'As I Lay Dying');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tyesha Hodkiewicz', 'Folklore', 23.52, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Roberto Franecki', 'Speech', 16.67, 'The Golden Apples of the Sun');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Britt Mitchell', 'Fairy tale', 33.6, 'A Glass of Blessings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cyril Lemke', 'Classic', 47.6, 'Ah, Wilderness!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Claud Nienow', 'Essay', 40.4, 'Little Hands Clapping');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Edward Stracke', 'Legend', 33.24, 'I Sing the Body Electric');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Janay Mueller', 'Horror', 18.85, 'The Man Within');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Candi Gottlieb', 'Essay', 44.25, 'Eyeless in Gaza');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Santana Lehner', 'Folklore', 37.84, 'A Time to Kill');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Claudette Nienow II', 'Narrative nonfiction', 23.19, 'The Torment of Others');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sadye Schuppe', 'Folklore', 29.89, 'Cover Her Face');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Jeffry Kuphal', 'Tall tale', 37.17, 'The Parliament of Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rudolf Bayer', 'Mythopoeia', 39.88, 'To Say Nothing of the Dog');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Justin Marks', 'Mystery', 20.09, 'Such, Such Were the Joys');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tamica Larson', 'Realistic fiction', 35.75, 'The Wives of Bath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Vanesa Wisoky', 'Essay', 16.73, 'Blue Remembered Earth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kylie Reichert DVM', 'Legend', 45.22, 'To a God Unknown');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Abdul Sauer', 'Speech', 35.44, 'An Evil Cradling');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Benjamin Gutmann', 'Mystery', 15.63, 'An Instant In The Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jacob Wiza', 'Mythopoeia', 39.84, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sergio Waters', 'Reference book', 42.12, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Wilhelmina Zulauf', 'Fanfiction', 11.83, 'Nectar in a Sieve');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Chauncey Welch', 'Horror', 20.71, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Sadye Hirthe', 'Fable', 13.6, 'Beyond the Mexique Bay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Federico Murray', 'Metafiction', 17.99, 'Taming a Sea Horse');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Donte Hegmann', 'Mythopoeia', 42.9, 'A Glass of Blessings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Arlena Schulist', 'Fairy tale', 18.76, 'Many Waters');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deandre Johnston', 'Narrative nonfiction', 19.42, 'Gone with the Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Winnie Orn', 'Historical fiction', 18.44, 'Edna O\'Brien');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maris Wisozk IV', 'Fanfiction', 30.97, 'A Scanner Darkly');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Sanford Nikolaus', 'Crime/Detective', 47.69, 'The Heart Is a Lonely Hunter');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charles Daugherty', 'Speech', 13.04, 'No Highway');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Barrett Nader', 'Fiction narrative', 13.64, 'Fair Stood the Wind for France');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shanon Labadie', 'Narrative nonfiction', 16.02, 'Frequent Hearses');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lawerence Lang', 'Tall tale', 27.66, 'Far From the Madding Crowd');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Darron Hintz', 'Realistic fiction', 39.01, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Madelene O\'Hara', 'Comic/Graphic Novel', 28.3, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Orval Jacobs', 'Folklore', 14.76, 'For Whom the Bell Tolls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lynell Labadie II', 'Classic', 42.37, 'That Good Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Quintin Bartoletti', 'Legend', 46.15, 'Terrible Swift Sword');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Jarod Hane', 'Reference book', 37.19, 'Look to Windward');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Darnell Luettgen', 'Reference book', 10.85, 'An Instant In The Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Emmanuel Shields', 'Metafiction', 33.08, 'The Last Enemy');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Candie Trantow', 'Tall tale', 33.35, 'The Violent Bear It Away');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Andria Schuppe', 'Humor', 20.86, 'The Man Within');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Tori West', 'Fanfiction', 26.37, 'The Far-Distant Oxus');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gordon Weimann', 'Horror', 47.54, 'Mother Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Misha Koepp', 'Humor', 25.24, 'Beyond the Mexique Bay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rodrigo Hayes', 'Horror', 19.02, 'Time of our Darkness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cori Schamberger', 'Fiction narrative', 32.1, 'The Way Through the Woods');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Elizebeth Kuhlman', 'Reference book', 27.6, 'Vile Bodies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Christina Kertzmann', 'Historical fiction', 41.28, 'The Wives of Bath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Britteny Davis II', 'Fiction narrative', 29.18, 'Vanity Fair');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kristina Vandervort I', 'Realistic fiction', 10.63, 'The Far-Distant Oxus');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cody Wolff', 'Narrative nonfiction', 29.18, 'The Proper Study');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kraig Erdman II', 'Fanfiction', 31.62, 'Look Homeward, Angel');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cathrine Lakin PhD', 'Humor', 39.86, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Elene Volkman', 'Fanfiction', 35.59, 'A Monstrous Regiment of Women');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Bernita DuBuque', 'Science fiction', 15.12, 'Death Be Not Proud');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Omer Block', 'Fairy tale', 33.09, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Davis Kuhlman', 'Classic', 17.62, 'Brandy of the Damned');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Waylon Schamberger', 'Tall tale', 30.3, 'The Heart Is Deceitful Above All Things');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charline Mante', 'Humor', 43.06, 'Wildfire at Midnight');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Raul Beier', 'Fable', 14.26, 'No Longer at Ease');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rosario Gleichner', 'Biography/Autobiography', 47.66, 'Recalled to Life');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tomasa Hilll', 'Classic', 19.43, 'From Here to Eternity');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('John Fritsch', 'Fairy tale', 44.78, 'For Whom the Bell Tolls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dell Lebsack', 'Crime/Detective', 39.74, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Boyd Haag', 'Historical fiction', 27.68, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Carmelita Blanda', 'Fantasy', 20.95, 'Pale Kings and Princes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Milo Cole', 'Fiction narrative', 21.48, 'East of Eden');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Grant Murray', 'Fanfiction', 20.85, 'The Parliament of Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Creola Bergnaum', 'Comic/Graphic Novel', 43.48, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sindy Fisher', 'Folklore', 30.69, 'Butter In a Lordly Dish');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maricruz Abernathy', 'Mythopoeia', 44.25, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Catherin Lehner', 'Folklore', 24.44, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gail Langosh', 'Fiction in verse', 21.02, 'Many Waters');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Britney Hudson', 'Fanfiction', 45.55, 'Pale Kings and Princes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leandro Kreiger', 'Suspense/Thriller', 35.44, 'Look to Windward');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Melani Quitzon', 'Suspense/Thriller', 10.15, 'The Waste Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Elroy Beier DVM', 'Legend', 21.4, 'I Will Fear No Evil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Socorro Dibbert', 'Metafiction', 17.28, 'The Man Within');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leola Moore', 'Mythology', 16.3, 'Little Hands Clapping');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Eldridge Rowe', 'Fable', 47.67, 'The Daffodil Sky');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Maryanna Runolfsdottir', 'Textbook', 17.23, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Glenna Heidenreich', 'Tall tale', 19.61, 'A Monstrous Regiment of Women');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Adrian Schmidt', 'Mythology', 27.95, 'Lilies of the Field');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Claudio Gibson', 'Fable', 20.11, 'Such, Such Were the Joys');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carroll Legros', 'Metafiction', 31.95, 'A Many-Splendoured Thing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Avery Rippin', 'Biography/Autobiography', 21.08, 'The Torment of Others');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. John Schiller', 'Fairy tale', 47.42, 'The Curious Incident of the Dog in the Night-Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shonta Wisoky', 'Comic/Graphic Novel', 42.31, 'From Here to Eternity');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('James Homenick', 'Legend', 28.79, 'Waiting for the Barbarians');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Paz Leffler', 'Mythology', 40.2, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lenora Stroman', 'Mystery', 47.14, 'Moab Is My Washpot');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cesar Hirthe', 'Crime/Detective', 24.06, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lina Heathcote', 'Fiction in verse', 28.39, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Myriam Jacobs DDS', 'Essay', 41.03, 'The Man Within');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deon Cole MD', 'Comic/Graphic Novel', 28.09, 'Time of our Darkness');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lisbeth Stark IV', 'Mythopoeia', 15.91, 'Look Homeward, Angel');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Natividad Koepp Jr.', 'Science fiction', 17.09, 'The Stars\' Tennis Balls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Delmer Gleichner Sr.', 'Science fiction', 30.48, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jan Johnston', 'Western', 47.12, 'Lilies of the Field');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Francis Zieme', 'Classic', 32.79, 'To Sail Beyond the Sunset');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Eugene Nader PhD', 'Fiction narrative', 14.68, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Yesenia Rau', 'Suspense/Thriller', 31.24, 'That Hideous Strength');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Gearldine Haley', 'Humor', 47.48, 'Specimen Days');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Roxane Glover', 'Textbook', 40.2, 'As I Lay Dying');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charley Herzog DVM', 'Textbook', 27.7, 'A Many-Splendoured Thing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Diedra Bradtke', 'Fanfiction', 36.2, 'The Little Foxes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Les Schmitt', 'Folklore', 45, 'Time To Murder And Create');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hugh Mayert', 'Fairy tale', 34.38, 'Beneath the Bleeding');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ismael Emmerich', 'Metafiction', 43.49, 'The Waste Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shanta Haley PhD', 'Metafiction', 25.77, 'Françoise Sagan');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Garret Schultz', 'Comic/Graphic Novel', 18.56, 'Beyond the Mexique Bay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Celia Kozey', 'Humor', 45.28, 'Consider Phlebas');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Floyd Cole', 'Metafiction', 37.43, 'Look Homeward, Angel');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Lisandra Roberts', 'Legend', 28.48, 'I Know Why the Caged Bird Sings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Elisha Hoeger', 'Realistic fiction', 31.61, 'The Moving Finger');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Darrin Stiedemann', 'Suspense/Thriller', 47.22, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Garret Graham', 'Biography/Autobiography', 11.49, 'As I Lay Dying');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Brianna Hoppe', 'Tall tale', 28.06, 'Oh! To be in England');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Trent Russel', 'Legend', 10.56, 'An Instant In The Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jere Ruecker', 'Legend', 18.05, 'A Scanner Darkly');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Anibal O\'Keefe', 'Western', 15.32, 'Quo Vadis');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Audrie Monahan', 'Essay', 26.44, 'Recalled to Life');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Thanh Morar', 'Narrative nonfiction', 29.38, 'The Violent Bear It Away');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Armandina Rau', 'Realistic fiction', 14.91, 'Absalom, Absalom!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sherwood Ward', 'Horror', 33.24, 'The Wealth of Nations');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Seymour Bergnaum', 'Essay', 38.07, 'Some Buried Caesar');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dortha Hodkiewicz', 'Metafiction', 37.37, 'Consider the Lilies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hermina Ratke', 'Tall tale', 45.14, 'Recalled to Life');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Erasmo Berge', 'Textbook', 39.57, 'Death Be Not Proud');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ha Daugherty III', 'Mythology', 15.96, 'The Mermaids Singing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charline Bayer', 'Fiction in verse', 33.98, 'O Pioneers!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gayle Schaden', 'Mythopoeia', 11.17, 'A Summer Bird-Cage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Corazon Mertz', 'Mythology', 32.41, 'Terrible Swift Sword');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Fatimah Bayer', 'Reference book', 43.03, 'The World, the Flesh and the Devil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Emerson Volkman', 'Crime/Detective', 40.52, 'Great Work of Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sol Hilpert', 'Metafiction', 42.56, 'That Good Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Joey Daugherty', 'Horror', 18.41, 'The Far-Distant Oxus');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Bruce O\'Conner', 'Fable', 20.99, 'Look to Windward');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Darron Langosh II', 'Fiction narrative', 32.42, 'Absalom, Absalom!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Milford DuBuque', 'Science fiction', 32.77, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Christiane Muller', 'Speech', 38.45, 'Sleep the Brave');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Johnie Kertzmann I', 'Classic', 12.02, 'The Golden Apples of the Sun');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('America Bartoletti', 'Mythology', 13.23, 'To Sail Beyond the Sunset');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kam Bernier', 'Horror', 12.49, 'What\'s Become of Waring');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Louie Ebert', 'Metafiction', 15.54, 'Oh! To be in England');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Adrian Schroeder', 'Suspense/Thriller', 18.4, 'Jesting Pilate');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jefferson Parker', 'Realistic fiction', 46.5, 'To Your Scattered Bodies Go');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dominic DuBuque', 'Fantasy', 20.62, 'The Last Temptation');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kristal Kassulke', 'Science fiction', 38.68, 'The Way Through the Woods');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ernie Champlin', 'Short story', 18.7, 'Eyeless in Gaza');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Cortney Reinger', 'Humor', 39.1, 'An Instant In The Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Britt Bartell', 'Historical fiction', 35.96, 'A Scanner Darkly');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Catherine Christiansen', 'Mythology', 13.4, 'Nectar in a Sieve');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Agnus Armstrong', 'Folklore', 16.36, 'Bury My Heart at Wounded Knee');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Amiee Abernathy', 'Fiction narrative', 35.69, 'Bury My Heart at Wounded Knee');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Britta Breitenberg', 'Narrative nonfiction', 43.15, 'No Longer at Ease');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tobias Okuneva', 'Fantasy', 40.24, 'Blue Remembered Earth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ulysses Stoltenberg', 'Realistic fiction', 25.22, 'This Lime Tree Bower');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Yung Blick V', 'Reference book', 31.97, 'Down to a Sunless Sea');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Gisele Wilkinson', 'Fiction in verse', 18.44, 'Taming a Sea Horse');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Catherin Donnelly Jr.', 'Fanfiction', 26.89, 'From Here to Eternity');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Rashad Greenfelder', 'Fiction in verse', 17.57, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Dorene Franecki', 'Reference book', 34.75, 'A Summer Bird-Cage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cortney Barton', 'Horror', 27.42, 'The Mermaids Singing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Demarcus Price', 'Crime/Detective', 17.23, 'The Stars\' Tennis Balls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Basil Casper', 'Mystery', 12.15, 'Frequent Hearses');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marica Stoltenberg', 'Suspense/Thriller', 29.45, 'The Way Through the Woods');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Manual Davis II', 'Comic/Graphic Novel', 44.1, 'Stranger in a Strange Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ashlie Littel', 'Fable', 37.26, 'All Passion Spent');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Fidel Murray', 'Reference book', 23.24, 'No Highway');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cheryle Wunsch', 'Biography/Autobiography', 23.08, 'Noli Me Tangere');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lewis Mosciski', 'Comic/Graphic Novel', 16.32, 'When the Green Woods Laugh');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Basil Roberts PhD', 'Mystery', 34.28, 'The Daffodil Sky');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hosea Pfeffer', 'Science fiction', 33.18, 'A Time to Kill');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mervin Watsica', 'Biography/Autobiography', 31.08, 'Ego Dominus Tuus');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ivory Goodwin', 'Horror', 36.69, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kris Deckow', 'Tall tale', 15.41, 'Cabbages and Kings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Galina Pouros', 'Humor', 20.71, 'The Other Side of Silence');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Evelynn Koss', 'Fanfiction', 15.19, 'The Wings of the Dove');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Merlyn Bosco', 'Mystery', 29.23, 'The House of Mirth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Janella Deckow', 'Tall tale', 44.37, 'Blue Remembered Earth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Daryl Kris Sr.', 'Realistic fiction', 42.72, 'The Little Foxes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deon Spinka', 'Realistic fiction', 33.6, 'The Soldier\'s Art');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marybeth Prohaska', 'Mythopoeia', 47.02, 'Quo Vadis');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rozella Hackett DDS', 'Fable', 39.05, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Alphonso Hessel', 'Fantasy', 28.45, 'Things Fall Apart');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Cynthia Haag', 'Science fiction', 41.89, 'To Sail Beyond the Sunset');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jacob Kris', 'Narrative nonfiction', 21.5, 'The Wives of Bath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Delsie Gulgowski', 'Historical fiction', 39.23, 'All Passion Spent');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('William Schiller V', 'Narrative nonfiction', 47.52, 'The Heart Is a Lonely Hunter');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mittie Medhurst I', 'Metafiction', 35.15, 'Oh! To be in England');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Felton Ebert MD', 'Metafiction', 27.3, 'The Grapes of Wrath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jenelle Weissnat', 'Essay', 22.16, 'Dance Dance Dance');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Cyndi Kunze DDS', 'Biography/Autobiography', 39.91, 'The Lathe of Heaven');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Anjanette Abbott MD', 'Reference book', 22.05, 'Of Human Bondage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jim Quigley II', 'Classic', 46.25, 'Far From the Madding Crowd');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jacob Homenick', 'Comic/Graphic Novel', 45.93, 'Edna O\'Brien');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Kim Gerlach', 'Science fiction', 32.62, 'A Many-Splendoured Thing');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jonathon Sauer', 'Classic', 23.18, 'A Passage to India');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jamee Gislason', 'Mystery', 29.53, 'Postern of Fate');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Amal Waelchi Sr.', 'Fiction in verse', 22.77, 'Jesting Pilate');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Idella McLaughlin', 'Suspense/Thriller', 34.67, 'By Grand Central Station I Sat Down and Wept');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Darius Jaskolski', 'Classic', 13.71, 'Number the Stars');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marvella Denesik Sr.', 'Crime/Detective', 30.77, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Russel Gutkowski DDS', 'Metafiction', 41.2, 'Fair Stood the Wind for France');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Jeramy Mayert', 'Fantasy', 37.69, 'The Moving Toyshop');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Temple Skiles', 'Folklore', 26.23, 'By Grand Central Station I Sat Down and Wept');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ariane Johns', 'Folklore', 10.45, 'An Acceptable Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Reinaldo Quitzon', 'Comic/Graphic Novel', 46.12, 'The Heart Is a Lonely Hunter');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Wendell Barrows', 'Realistic fiction', 34.85, 'Blue Remembered Earth');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Greta Borer Jr.', 'Fantasy', 29.4, 'The Moving Toyshop');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kindra Schuster', 'Narrative nonfiction', 11.7, 'An Acceptable Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rubi Schamberger', 'Textbook', 42.08, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Fausto Collier', 'Western', 25.92, 'The Wealth of Nations');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ferdinand Anderson', 'Speech', 28.28, 'I Will Fear No Evil');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Benedict Zemlak', 'Western', 12.22, 'Let Us Now Praise Famous Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Huey Kreiger', 'Legend', 24.81, 'This Side of Paradise');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ramiro Goyette II', 'Realistic fiction', 11.11, 'The Golden Bowl');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ossie Mante Sr.', 'Western', 31.2, 'East of Eden');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marcos Dooley V', 'Classic', 15.3, 'In a Dry Season');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Miles Bailey', 'Humor', 30.07, 'All Passion Spent');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sharilyn McLaughlin', 'Biography/Autobiography', 26.37, 'The Lathe of Heaven');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Stefan Corkery', 'Science fiction', 27.57, 'His Dark Materials');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Samuel Hand', 'Fiction narrative', 30.33, 'Look Homeward, Angel');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rosamaria Corwin IV', 'Narrative nonfiction', 29.48, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Charlie Wintheiser', 'Fiction in verse', 15.85, 'Terrible Swift Sword');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Collin Fay', 'Mythology', 41.5, 'Wildfire at Midnight');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marquis Denesik', 'Classic', 37.01, 'Beyond the Mexique Bay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deangelo Macejkovic PhD', 'Legend', 35.3, 'A Monstrous Regiment of Women');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lucius Hauck', 'Mythopoeia', 12.63, 'Ah, Wilderness!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miesha Brown', 'Metafiction', 28.69, 'Ah, Wilderness!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marlin Nitzsche', 'Tall tale', 11.2, 'O Pioneers!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Lonna Lesch', 'Legend', 24.29, 'A Handful of Dust');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Myra Ebert', 'Fable', 32.6, 'Beneath the Bleeding');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Franchesca Powlowski', 'Horror', 29.33, 'Butter In a Lordly Dish');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Steven Cartwright DVM', 'Biography/Autobiography', 14.77, 'A Swiftly Tilting Planet');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Ciara Torphy', 'Speech', 22.73, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Luise Smitham I', 'Fiction narrative', 40.78, 'A Confederacy of Dunces');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carlos Hansen DVM', 'Classic', 24.71, 'Ring of Bright Water');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mohammad Bins MD', 'Horror', 39.9, 'Oh! To be in England');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kimbra O\'Keefe', 'Realistic fiction', 23.16, 'The Parliament of Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jeremiah Bogisich', 'Metafiction', 42.4, 'For a Breath I Tarry');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Harlan Kiehn Jr.', 'Folklore', 14.86, 'Stranger in a Strange Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Trent Jones', 'Crime/Detective', 17.76, 'Blood\'s a Rover');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Chelsie Wisozk', 'Classic', 32.25, 'Specimen Days');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Alona Weissnat I', 'Short story', 32.08, 'Beneath the Bleeding');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Hue Renner', 'Folklore', 27.9, 'Great Work of Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nathanial Osinski', 'Fiction in verse', 12.06, 'The Grapes of Wrath');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Nathanial Jacobs', 'Fiction narrative', 45.8, 'To Sail Beyond the Sunset');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Rolf Russel', 'Tall tale', 43.78, 'Ring of Bright Water');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Luke Bartoletti', 'Short story', 29.98, 'Mother Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deandra Hickle', 'Mythology', 44.64, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Agripina Howe', 'Reference book', 31.57, 'The Millstone');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Roderick Koelpin', 'Textbook', 29.89, 'For Whom the Bell Tolls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Sidney Bergnaum', 'Speech', 23.19, 'Cabbages and Kings');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Terrence VonRueden V', 'Tall tale', 23.94, 'Pale Kings and Princes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Aron Jacobs', 'Fable', 45.9, 'What\'s Become of Waring');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leif Bergstrom', 'Fairy tale', 47.47, 'Number the Stars');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Johnson Lind', 'Fiction in verse', 45.82, 'O Jerusalem!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ali Powlowski II', 'Historical fiction', 44.98, 'That Hideous Strength');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Sudie Russel', 'Biography/Autobiography', 16.75, 'The Mirror Crack\'d from Side to Side');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Matt Koepp MD', 'Legend', 14.87, 'In Dubious Battle');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Manuel Hand', 'Historical fiction', 27.64, 'When the Green Woods Laugh');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Neida Veum', 'Suspense/Thriller', 10.22, 'A Summer Bird-Cage');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Joesph Bauch', 'Fable', 18.98, 'Consider Phlebas');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Octavio Smith I', 'Suspense/Thriller', 23.96, 'Everything is Illuminated');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Christene Schneider', 'Textbook', 11.99, 'The Lathe of Heaven');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ping Gleason', 'Speech', 40.15, 'Things Fall Apart');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Shantel Hahn', 'Legend', 34.98, 'Beyond the Mexique Bay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Felipe Blick', 'Science fiction', 19.71, 'Recalled to Life');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lamar Kreiger', 'Tall tale', 47.85, 'Where Angels Fear to Tread');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Marcel Hills MD', 'Folklore', 32.92, 'Arms and the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leroy Stanton', 'Western', 16.87, 'Down to a Sunless Sea');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Wes Nader', 'Narrative nonfiction', 40.18, 'Behold the Man');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mrs. Gavin Haag', 'Comic/Graphic Novel', 39.66, 'Endless Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Darcie Lind', 'Tall tale', 40.94, 'A Confederacy of Dunces');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Julieann Wisoky V', 'Fantasy', 36.02, 'The Moon by Night');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Greta Aufderhar', 'Fairy tale', 44.81, 'Stranger in a Strange Land');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Leopoldo Mayert I', 'Tall tale', 15.3, 'For Whom the Bell Tolls');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Bev D\'Amore', 'Horror', 10.56, 'Great Work of Time');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Aiko Romaguera', 'Crime/Detective', 29.17, 'No Country for Old Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Adan Bechtelar', 'Suspense/Thriller', 28.12, 'Noli Me Tangere');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Foster Streich', 'Crime/Detective', 27.24, 'Fame Is the Spur');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mendy Walker Jr.', 'Classic', 17.93, 'Wildfire at Midnight');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Luann Rutherford Jr.', 'Historical fiction', 21.5, 'A Scanner Darkly');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Trena Paucek', 'Mystery', 35.49, 'From Here to Eternity');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Loren Rogahn', 'Western', 13.08, 'Bury My Heart at Wounded Knee');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Miss Jamal Erdman', 'Reference book', 31.06, 'Edna O\'Brien');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Marcell Huels', 'Legend', 10.57, 'This Lime Tree Bower');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Alecia Stiedemann', 'Reference book', 12.84, 'Rosemary Sutcliff');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Johnathan Schmitt', 'Fable', 12.78, 'Absalom, Absalom!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Tracy Cronin', 'Essay', 45.83, 'Antic Hay');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Eddie Weber', 'Comic/Graphic Novel', 21.9, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Raymon Marquardt', 'Fable', 19.39, 'For a Breath I Tarry');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Wes Kautzer', 'Metafiction', 33.64, 'Vile Bodies');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Mr. Daniel Rosenbaum', 'Western', 46, 'The Violent Bear It Away');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Deonna Bailey', 'Western', 32.63, 'Ah, Wilderness!');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Yajaira Gibson', 'Fairy tale', 28.73, 'Have His Carcase');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Lucia Block', 'Suspense/Thriller', 14.71, 'A Farewell to Arms');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Dr. Darrel Kub', 'Short story', 19.22, 'An Instant In The Wind');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Meridith Waters IV', 'Crime/Detective', 32.02, 'Jacob Have I Loved');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Carolyne Stamm III', 'Fairy tale', 36.49, 'A Scanner Darkly');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Ms. Jamel Bogisich', 'Narrative nonfiction', 27.04, 'The Needle\'s Eye');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Eli Lebsack', 'Essay', 36.92, 'Dulce et Decorum Est');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Jone Graham', 'Horror', 29.58, 'Now Sleeps the Crimson Petal');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Kristina Heidenreich', 'Tall tale', 24.33, 'Unweaving the Rainbow');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Etta Cummings', 'Mythopoeia', 35.09, 'Pale Kings and Princes');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Buddy Padberg', 'Fiction in verse', 15.57, 'No Country for Old Men');
INSERT INTO jpa_native_query.books (author, genre, price, title) VALUES ('Denyse Hoeger', 'Speech', 25.83, 'Those Barren Leaves, Thrones, Dominations');
